### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by edwardruthven** [arduino-libraries/Arduino_AdvancedAnalog#80]
C:\Users\Edward\AppData\Local\Temp\.arduinoIDE-unsaved2024811-24040-j7j4f9.d3p4\sketch_sep11a\sketch_sep11a.ino:1:10: fatal error: D:\Users\Edward\OneDrive\Documents\Arduino\libraries\Arduino_AdvancedAnalog\src/Arduino_AdvancedAnalog.h: Permission denied
 #include <Arduino_AdvancedAnalog.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: D:\Users\Edward\OneDrive\Documents\Arduino\libraries\Arduino_AdvancedAnalog\src/Arduino_AdvancedAnalog.h: Permission denied

**Comment by per1234** [comment]
Hi @edwardruthven. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. The error you are encountering is caused by some problem with your computer rather than anything specific to the codebase that is hosted in this repository. So this topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
